<?php
/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function mytheme_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  // Get Request Object.
  $request = Drupal::request();

  // If there is HTTP Exception..
  if ($exception = $request->attributes->get('exception')) {
    // Get the status code.
    $status_code = $exception->getStatusCode();
    if (in_array($status_code, array(403, 404))) {
      $suggestions[] = 'page__' . $status_code;
    }
  }
}